const products = [
    {
        _id:'1',
        name:'Iphone13 5g',
        image:'/images/cellphone1.jpg',
        description:'descriptive meaning',
        brand:'apple',
        category:'electronics',
        countinStocks:10,
        price:89.90,
        rating:4,
        numberofReviews:4,

    },
    {
        _id:'2',
        name:'Iphone13 xcelent',
        image:'/images/cellphone2.jpg',
        description:'descriptive meaning',
        brand:'apple',
        category:'electronics',
        countinStocks:20,
        price:99.90,
        rating:5,
        numberofReviews:6,
    },
    {
        _id:'3',
        name:'Iphone13 Pro5g',
        image:'/images/cellphone3.jpg',
        description:'descriptive meaning',
        brand:'apple',
        category:'electronics',
        countinStocks:20,
        price:99.90,
        rating:3,
        numberofReviews:6,
    },
    {
        _id:'4',
        name:'Iphone13-x',
        image:'/images/cellphone4.jpg',
        description:'descriptive meaning',
        brand:'apple',
        category:'electronics',
        countinStocks:20,
        price:99.90,
        rating:3,
        numberofReviews:6,
    },
    {
        _id:'5',
        name:'Samsung galaxy Pro',
        image:'/images/cellphone5.jpg',
        description:'descriptive meaning',
        brand:'apple',
        category:'electronics',
        countinStocks:20,
        price:99.90,
        rating:1,
        numberofReviews:6,
    },
    {
        _id:'6',
        name:'Iphone12 Pro',
        image:'/images/cellphone6.jpg',
        description:'descriptive meaning',
        brand:'apple',
        category:'electronics',
        countinStocks:20,
        price:99.90,
        rating:2,
        numberofReviews:6,
    },
]

export default products